# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Form.ui'
##
## Created by: Qt User Interface Compiler version 6.2.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QLineEdit, QListWidget, QListWidgetItem, QPushButton,
    QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(749, 443)
        self.label_9 = QLabel(Form)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(260, 360, 150, 16))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_10 = QLabel(Form)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 360, 150, 16))
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setFont(font)
        self.MiddleRadiusSmall = QLineEdit(Form)
        self.MiddleRadiusSmall.setObjectName(u"MiddleRadiusSmall")
        self.MiddleRadiusSmall.setGeometry(QRect(400, 360, 40, 16))
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.MiddleRadiusSmall.sizePolicy().hasHeightForWidth())
        self.MiddleRadiusSmall.setSizePolicy(sizePolicy1)
        self.MiddleRadiusLarge = QLineEdit(Form)
        self.MiddleRadiusLarge.setObjectName(u"MiddleRadiusLarge")
        self.MiddleRadiusLarge.setGeometry(QRect(150, 360, 40, 16))
        sizePolicy1.setHeightForWidth(self.MiddleRadiusLarge.sizePolicy().hasHeightForWidth())
        self.MiddleRadiusLarge.setSizePolicy(sizePolicy1)
        self.pushButton = QPushButton(Form)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(650, 360, 75, 23))
        self.OpenATemp = QPushButton(Form)
        self.OpenATemp.setObjectName(u"OpenATemp")
        self.OpenATemp.setGeometry(QRect(5, 5, 91, 23))
        self.label_27 = QLabel(Form)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(105, 5, 400, 23))
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 40, 70, 21))
        sizePolicy1.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy1)
        font1 = QFont()
        font1.setPointSize(13)
        self.label.setFont(font1)
        self.label_11 = QLabel(Form)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(260, 40, 70, 21))
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setFont(font1)
        self.label_19 = QLabel(Form)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(510, 40, 70, 21))
        sizePolicy1.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy1)
        self.label_19.setFont(font1)
        self.widget = QWidget(Form)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(10, 240, 181, 18))
        self.horizontalLayout_5 = QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label_4 = QLabel(self.widget)
        self.label_4.setObjectName(u"label_4")
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setFont(font)

        self.horizontalLayout_5.addWidget(self.label_4)

        self.LayerNumber1 = QLineEdit(self.widget)
        self.LayerNumber1.setObjectName(u"LayerNumber1")
        sizePolicy.setHeightForWidth(self.LayerNumber1.sizePolicy().hasHeightForWidth())
        self.LayerNumber1.setSizePolicy(sizePolicy)
        self.LayerNumber1.setMinimumSize(QSize(40, 0))
        self.LayerNumber1.setMaximumSize(QSize(40, 16))

        self.horizontalLayout_5.addWidget(self.LayerNumber1)

        self.label_36 = QLabel(Form)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 415, 360, 20))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(85, 255, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(170, 255, 127, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(127, 255, 63, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        brush4 = QBrush(QColor(42, 127, 0, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush4)
        brush5 = QBrush(QColor(56, 170, 0, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush6 = QBrush(QColor(255, 255, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush7 = QBrush(QColor(255, 255, 127, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush7)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        brush8 = QBrush(QColor(85, 255, 127, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.NoRole, brush8)
        brush9 = QBrush(QColor(255, 255, 220, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush9)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush7)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.NoRole, brush8)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush9)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.NoRole, brush8)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush9)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        self.label_36.setPalette(palette)
        self.label_36.setFrameShape(QFrame.Panel)
        self.label_37 = QLabel(Form)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(10, 390, 105, 20))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Active, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Active, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        palette1.setBrush(QPalette.Active, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush7)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Active, QPalette.AlternateBase, brush2)
        palette1.setBrush(QPalette.Active, QPalette.NoRole, brush8)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipBase, brush9)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Inactive, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Inactive, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.NoRole, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush9)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.Dark, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Mid, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.BrightText, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.ButtonText, brush4)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.Shadow, brush)
        palette1.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush1)
        palette1.setBrush(QPalette.Disabled, QPalette.NoRole, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush9)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        self.label_37.setPalette(palette1)
        self.label_37.setFrameShape(QFrame.Panel)
        self.widget1 = QWidget(Form)
        self.widget1.setObjectName(u"widget1")
        self.widget1.setGeometry(QRect(10, 270, 181, 18))
        self.horizontalLayout_6 = QHBoxLayout(self.widget1)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.widget1)
        self.label_5.setObjectName(u"label_5")
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setFont(font)

        self.horizontalLayout_6.addWidget(self.label_5)

        self.TurnsNumber1 = QLineEdit(self.widget1)
        self.TurnsNumber1.setObjectName(u"TurnsNumber1")
        sizePolicy.setHeightForWidth(self.TurnsNumber1.sizePolicy().hasHeightForWidth())
        self.TurnsNumber1.setSizePolicy(sizePolicy)
        self.TurnsNumber1.setMinimumSize(QSize(40, 0))
        self.TurnsNumber1.setMaximumSize(QSize(40, 16))

        self.horizontalLayout_6.addWidget(self.TurnsNumber1)

        self.widget2 = QWidget(Form)
        self.widget2.setObjectName(u"widget2")
        self.widget2.setGeometry(QRect(10, 300, 181, 18))
        self.horizontalLayout_7 = QHBoxLayout(self.widget2)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.label_7 = QLabel(self.widget2)
        self.label_7.setObjectName(u"label_7")
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setFont(font)

        self.horizontalLayout_7.addWidget(self.label_7)

        self.InnerRadius1 = QLineEdit(self.widget2)
        self.InnerRadius1.setObjectName(u"InnerRadius1")
        sizePolicy.setHeightForWidth(self.InnerRadius1.sizePolicy().hasHeightForWidth())
        self.InnerRadius1.setSizePolicy(sizePolicy)
        self.InnerRadius1.setMinimumSize(QSize(40, 0))
        self.InnerRadius1.setMaximumSize(QSize(40, 16))

        self.horizontalLayout_7.addWidget(self.InnerRadius1)

        self.widget3 = QWidget(Form)
        self.widget3.setObjectName(u"widget3")
        self.widget3.setGeometry(QRect(10, 330, 181, 18))
        self.horizontalLayout_8 = QHBoxLayout(self.widget3)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.label_8 = QLabel(self.widget3)
        self.label_8.setObjectName(u"label_8")
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setFont(font)

        self.horizontalLayout_8.addWidget(self.label_8)

        self.OuterRadius1 = QLineEdit(self.widget3)
        self.OuterRadius1.setObjectName(u"OuterRadius1")
        sizePolicy.setHeightForWidth(self.OuterRadius1.sizePolicy().hasHeightForWidth())
        self.OuterRadius1.setSizePolicy(sizePolicy)
        self.OuterRadius1.setMinimumSize(QSize(40, 0))
        self.OuterRadius1.setMaximumSize(QSize(40, 16))

        self.horizontalLayout_8.addWidget(self.OuterRadius1)

        self.widget4 = QWidget(Form)
        self.widget4.setObjectName(u"widget4")
        self.widget4.setGeometry(QRect(260, 240, 181, 18))
        self.horizontalLayout_12 = QHBoxLayout(self.widget4)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.label_15 = QLabel(self.widget4)
        self.label_15.setObjectName(u"label_15")
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setFont(font)

        self.horizontalLayout_12.addWidget(self.label_15)

        self.LayerNumber2 = QLineEdit(self.widget4)
        self.LayerNumber2.setObjectName(u"LayerNumber2")
        sizePolicy.setHeightForWidth(self.LayerNumber2.sizePolicy().hasHeightForWidth())
        self.LayerNumber2.setSizePolicy(sizePolicy)
        self.LayerNumber2.setMinimumSize(QSize(40, 0))
        self.LayerNumber2.setMaximumSize(QSize(40, 16))

        self.horizontalLayout_12.addWidget(self.LayerNumber2)

        self.widget5 = QWidget(Form)
        self.widget5.setObjectName(u"widget5")
        self.widget5.setGeometry(QRect(260, 270, 181, 18))
        self.horizontalLayout_13 = QHBoxLayout(self.widget5)
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.label_16 = QLabel(self.widget5)
        self.label_16.setObjectName(u"label_16")
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setFont(font)

        self.horizontalLayout_13.addWidget(self.label_16)

        self.TurnsNumber2 = QLineEdit(self.widget5)
        self.TurnsNumber2.setObjectName(u"TurnsNumber2")
        sizePolicy.setHeightForWidth(self.TurnsNumber2.sizePolicy().hasHeightForWidth())
        self.TurnsNumber2.setSizePolicy(sizePolicy)
        self.TurnsNumber2.setMinimumSize(QSize(40, 0))
        self.TurnsNumber2.setMaximumSize(QSize(40, 16))

        self.horizontalLayout_13.addWidget(self.TurnsNumber2)

        self.widget6 = QWidget(Form)
        self.widget6.setObjectName(u"widget6")
        self.widget6.setGeometry(QRect(260, 300, 181, 18))
        self.horizontalLayout_14 = QHBoxLayout(self.widget6)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.label_17 = QLabel(self.widget6)
        self.label_17.setObjectName(u"label_17")
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setFont(font)

        self.horizontalLayout_14.addWidget(self.label_17)

        self.InnerRadius2 = QLineEdit(self.widget6)
        self.InnerRadius2.setObjectName(u"InnerRadius2")
        sizePolicy.setHeightForWidth(self.InnerRadius2.sizePolicy().hasHeightForWidth())
        self.InnerRadius2.setSizePolicy(sizePolicy)
        self.InnerRadius2.setMinimumSize(QSize(40, 0))
        self.InnerRadius2.setMaximumSize(QSize(40, 16))

        self.horizontalLayout_14.addWidget(self.InnerRadius2)

        self.widget7 = QWidget(Form)
        self.widget7.setObjectName(u"widget7")
        self.widget7.setGeometry(QRect(260, 330, 181, 18))
        self.horizontalLayout_15 = QHBoxLayout(self.widget7)
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.label_18 = QLabel(self.widget7)
        self.label_18.setObjectName(u"label_18")
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setFont(font)

        self.horizontalLayout_15.addWidget(self.label_18)

        self.OuterRadius2 = QLineEdit(self.widget7)
        self.OuterRadius2.setObjectName(u"OuterRadius2")
        sizePolicy.setHeightForWidth(self.OuterRadius2.sizePolicy().hasHeightForWidth())
        self.OuterRadius2.setSizePolicy(sizePolicy)
        self.OuterRadius2.setMinimumSize(QSize(40, 0))
        self.OuterRadius2.setMaximumSize(QSize(40, 16))

        self.horizontalLayout_15.addWidget(self.OuterRadius2)

        self.widget8 = QWidget(Form)
        self.widget8.setObjectName(u"widget8")
        self.widget8.setGeometry(QRect(510, 240, 181, 18))
        self.horizontalLayout_18 = QHBoxLayout(self.widget8)
        self.horizontalLayout_18.setObjectName(u"horizontalLayout_18")
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.label_23 = QLabel(self.widget8)
        self.label_23.setObjectName(u"label_23")
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setFont(font)

        self.horizontalLayout_18.addWidget(self.label_23)

        self.LayerNumber3 = QLineEdit(self.widget8)
        self.LayerNumber3.setObjectName(u"LayerNumber3")
        sizePolicy1.setHeightForWidth(self.LayerNumber3.sizePolicy().hasHeightForWidth())
        self.LayerNumber3.setSizePolicy(sizePolicy1)
        self.LayerNumber3.setMinimumSize(QSize(40, 0))
        self.LayerNumber3.setMaximumSize(QSize(40, 16))

        self.horizontalLayout_18.addWidget(self.LayerNumber3)

        self.widget9 = QWidget(Form)
        self.widget9.setObjectName(u"widget9")
        self.widget9.setGeometry(QRect(510, 270, 181, 18))
        self.horizontalLayout_19 = QHBoxLayout(self.widget9)
        self.horizontalLayout_19.setObjectName(u"horizontalLayout_19")
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.label_24 = QLabel(self.widget9)
        self.label_24.setObjectName(u"label_24")
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setFont(font)

        self.horizontalLayout_19.addWidget(self.label_24)

        self.TurnsNumber3 = QLineEdit(self.widget9)
        self.TurnsNumber3.setObjectName(u"TurnsNumber3")
        sizePolicy1.setHeightForWidth(self.TurnsNumber3.sizePolicy().hasHeightForWidth())
        self.TurnsNumber3.setSizePolicy(sizePolicy1)
        self.TurnsNumber3.setMinimumSize(QSize(40, 0))
        self.TurnsNumber3.setMaximumSize(QSize(40, 16))

        self.horizontalLayout_19.addWidget(self.TurnsNumber3)

        self.widget10 = QWidget(Form)
        self.widget10.setObjectName(u"widget10")
        self.widget10.setGeometry(QRect(510, 300, 181, 18))
        self.horizontalLayout_20 = QHBoxLayout(self.widget10)
        self.horizontalLayout_20.setObjectName(u"horizontalLayout_20")
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.label_25 = QLabel(self.widget10)
        self.label_25.setObjectName(u"label_25")
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setFont(font)

        self.horizontalLayout_20.addWidget(self.label_25)

        self.InnerRadius3 = QLineEdit(self.widget10)
        self.InnerRadius3.setObjectName(u"InnerRadius3")
        sizePolicy1.setHeightForWidth(self.InnerRadius3.sizePolicy().hasHeightForWidth())
        self.InnerRadius3.setSizePolicy(sizePolicy1)
        self.InnerRadius3.setMinimumSize(QSize(40, 0))
        self.InnerRadius3.setMaximumSize(QSize(40, 16))

        self.horizontalLayout_20.addWidget(self.InnerRadius3)

        self.widget11 = QWidget(Form)
        self.widget11.setObjectName(u"widget11")
        self.widget11.setGeometry(QRect(510, 330, 181, 18))
        self.horizontalLayout_21 = QHBoxLayout(self.widget11)
        self.horizontalLayout_21.setObjectName(u"horizontalLayout_21")
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.label_26 = QLabel(self.widget11)
        self.label_26.setObjectName(u"label_26")
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setFont(font)

        self.horizontalLayout_21.addWidget(self.label_26)

        self.OuterRadius3 = QLineEdit(self.widget11)
        self.OuterRadius3.setObjectName(u"OuterRadius3")
        sizePolicy1.setHeightForWidth(self.OuterRadius3.sizePolicy().hasHeightForWidth())
        self.OuterRadius3.setSizePolicy(sizePolicy1)
        self.OuterRadius3.setMinimumSize(QSize(40, 0))
        self.OuterRadius3.setMaximumSize(QSize(40, 16))

        self.horizontalLayout_21.addWidget(self.OuterRadius3)

        self.widget12 = QWidget(Form)
        self.widget12.setObjectName(u"widget12")
        self.widget12.setGeometry(QRect(10, 60, 222, 52))
        self.horizontalLayout = QHBoxLayout(self.widget12)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.widget12)
        self.label_2.setObjectName(u"label_2")
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QSize(0, 0))
        self.label_2.setFont(font)

        self.horizontalLayout.addWidget(self.label_2)

        self.CoilsType1 = QListWidget(self.widget12)
        QListWidgetItem(self.CoilsType1)
        QListWidgetItem(self.CoilsType1)
        self.CoilsType1.setObjectName(u"CoilsType1")
        sizePolicy1.setHeightForWidth(self.CoilsType1.sizePolicy().hasHeightForWidth())
        self.CoilsType1.setSizePolicy(sizePolicy1)
        self.CoilsType1.setMinimumSize(QSize(0, 0))
        self.CoilsType1.setMaximumSize(QSize(155, 50))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.CoilsType1.setFont(font2)

        self.horizontalLayout.addWidget(self.CoilsType1)

        self.widget13 = QWidget(Form)
        self.widget13.setObjectName(u"widget13")
        self.widget13.setGeometry(QRect(260, 60, 222, 52))
        self.horizontalLayout_3 = QHBoxLayout(self.widget13)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_20 = QLabel(self.widget13)
        self.label_20.setObjectName(u"label_20")
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QSize(0, 41))
        self.label_20.setFont(font)

        self.horizontalLayout_3.addWidget(self.label_20)

        self.CoilsType2 = QListWidget(self.widget13)
        QListWidgetItem(self.CoilsType2)
        QListWidgetItem(self.CoilsType2)
        self.CoilsType2.setObjectName(u"CoilsType2")
        sizePolicy1.setHeightForWidth(self.CoilsType2.sizePolicy().hasHeightForWidth())
        self.CoilsType2.setSizePolicy(sizePolicy1)
        self.CoilsType2.setMinimumSize(QSize(130, 41))
        self.CoilsType2.setMaximumSize(QSize(155, 50))

        self.horizontalLayout_3.addWidget(self.CoilsType2)

        self.widget14 = QWidget(Form)
        self.widget14.setObjectName(u"widget14")
        self.widget14.setGeometry(QRect(510, 60, 222, 52))
        self.horizontalLayout_9 = QHBoxLayout(self.widget14)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.label_12 = QLabel(self.widget14)
        self.label_12.setObjectName(u"label_12")
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QSize(0, 41))
        self.label_12.setFont(font)

        self.horizontalLayout_9.addWidget(self.label_12)

        self.CoilsType3 = QListWidget(self.widget14)
        QListWidgetItem(self.CoilsType3)
        QListWidgetItem(self.CoilsType3)
        self.CoilsType3.setObjectName(u"CoilsType3")
        sizePolicy1.setHeightForWidth(self.CoilsType3.sizePolicy().hasHeightForWidth())
        self.CoilsType3.setSizePolicy(sizePolicy1)
        self.CoilsType3.setMinimumSize(QSize(130, 41))
        self.CoilsType3.setMaximumSize(QSize(155, 50))

        self.horizontalLayout_9.addWidget(self.CoilsType3)

        self.widget15 = QWidget(Form)
        self.widget15.setObjectName(u"widget15")
        self.widget15.setGeometry(QRect(10, 120, 141, 47))
        self.horizontalLayout_2 = QHBoxLayout(self.widget15)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.widget15)
        self.label_3.setObjectName(u"label_3")
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QSize(0, 0))
        self.label_3.setFont(font)

        self.horizontalLayout_2.addWidget(self.label_3)

        self.Type1 = QListWidget(self.widget15)
        QListWidgetItem(self.Type1)
        QListWidgetItem(self.Type1)
        self.Type1.setObjectName(u"Type1")
        sizePolicy.setHeightForWidth(self.Type1.sizePolicy().hasHeightForWidth())
        self.Type1.setSizePolicy(sizePolicy)
        self.Type1.setMinimumSize(QSize(60, 41))
        self.Type1.setMaximumSize(QSize(70, 45))

        self.horizontalLayout_2.addWidget(self.Type1)

        self.widget16 = QWidget(Form)
        self.widget16.setObjectName(u"widget16")
        self.widget16.setGeometry(QRect(260, 120, 141, 47))
        self.horizontalLayout_4 = QHBoxLayout(self.widget16)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_13 = QLabel(self.widget16)
        self.label_13.setObjectName(u"label_13")
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QSize(0, 41))
        self.label_13.setFont(font)

        self.horizontalLayout_4.addWidget(self.label_13)

        self.Type2 = QListWidget(self.widget16)
        QListWidgetItem(self.Type2)
        QListWidgetItem(self.Type2)
        self.Type2.setObjectName(u"Type2")
        sizePolicy.setHeightForWidth(self.Type2.sizePolicy().hasHeightForWidth())
        self.Type2.setSizePolicy(sizePolicy)
        self.Type2.setMinimumSize(QSize(60, 41))
        self.Type2.setMaximumSize(QSize(70, 45))

        self.horizontalLayout_4.addWidget(self.Type2)

        self.widget17 = QWidget(Form)
        self.widget17.setObjectName(u"widget17")
        self.widget17.setGeometry(QRect(510, 120, 141, 47))
        self.horizontalLayout_10 = QHBoxLayout(self.widget17)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.label_21 = QLabel(self.widget17)
        self.label_21.setObjectName(u"label_21")
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QSize(0, 41))
        self.label_21.setFont(font)

        self.horizontalLayout_10.addWidget(self.label_21)

        self.Type3 = QListWidget(self.widget17)
        QListWidgetItem(self.Type3)
        QListWidgetItem(self.Type3)
        self.Type3.setObjectName(u"Type3")
        sizePolicy1.setHeightForWidth(self.Type3.sizePolicy().hasHeightForWidth())
        self.Type3.setSizePolicy(sizePolicy1)
        self.Type3.setMinimumSize(QSize(60, 41))
        self.Type3.setMaximumSize(QSize(70, 45))

        self.horizontalLayout_10.addWidget(self.Type3)

        self.widget18 = QWidget(Form)
        self.widget18.setObjectName(u"widget18")
        self.widget18.setGeometry(QRect(10, 180, 141, 47))
        self.horizontalLayout_11 = QHBoxLayout(self.widget18)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.label_6 = QLabel(self.widget18)
        self.label_6.setObjectName(u"label_6")
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QSize(0, 0))
        self.label_6.setFont(font)

        self.horizontalLayout_11.addWidget(self.label_6)

        self.Length1 = QListWidget(self.widget18)
        QListWidgetItem(self.Length1)
        QListWidgetItem(self.Length1)
        self.Length1.setObjectName(u"Length1")
        sizePolicy.setHeightForWidth(self.Length1.sizePolicy().hasHeightForWidth())
        self.Length1.setSizePolicy(sizePolicy)
        self.Length1.setMinimumSize(QSize(60, 41))
        self.Length1.setMaximumSize(QSize(70, 45))

        self.horizontalLayout_11.addWidget(self.Length1)

        self.widget19 = QWidget(Form)
        self.widget19.setObjectName(u"widget19")
        self.widget19.setGeometry(QRect(260, 180, 141, 47))
        self.horizontalLayout_16 = QHBoxLayout(self.widget19)
        self.horizontalLayout_16.setObjectName(u"horizontalLayout_16")
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.label_14 = QLabel(self.widget19)
        self.label_14.setObjectName(u"label_14")
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QSize(0, 41))
        self.label_14.setFont(font)

        self.horizontalLayout_16.addWidget(self.label_14)

        self.Length2 = QListWidget(self.widget19)
        QListWidgetItem(self.Length2)
        QListWidgetItem(self.Length2)
        self.Length2.setObjectName(u"Length2")
        sizePolicy.setHeightForWidth(self.Length2.sizePolicy().hasHeightForWidth())
        self.Length2.setSizePolicy(sizePolicy)
        self.Length2.setMinimumSize(QSize(60, 41))
        self.Length2.setMaximumSize(QSize(70, 45))

        self.horizontalLayout_16.addWidget(self.Length2)

        self.widget20 = QWidget(Form)
        self.widget20.setObjectName(u"widget20")
        self.widget20.setGeometry(QRect(510, 180, 141, 47))
        self.horizontalLayout_17 = QHBoxLayout(self.widget20)
        self.horizontalLayout_17.setObjectName(u"horizontalLayout_17")
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.label_22 = QLabel(self.widget20)
        self.label_22.setObjectName(u"label_22")
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QSize(0, 41))
        self.label_22.setFont(font)

        self.horizontalLayout_17.addWidget(self.label_22)

        self.Length3 = QListWidget(self.widget20)
        QListWidgetItem(self.Length3)
        QListWidgetItem(self.Length3)
        self.Length3.setObjectName(u"Length3")
        sizePolicy1.setHeightForWidth(self.Length3.sizePolicy().hasHeightForWidth())
        self.Length3.setSizePolicy(sizePolicy1)
        self.Length3.setMinimumSize(QSize(60, 41))
        self.Length3.setMaximumSize(QSize(70, 45))

        self.horizontalLayout_17.addWidget(self.Length3)


        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"Middle Radius Small", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Middle Radius Large", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"Save", None))
        self.OpenATemp.setText(QCoreApplication.translate("Form", u"Open a Template", None))
        self.label_27.setText("")
        self.label.setText(QCoreApplication.translate("Form", u"Coil 1", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"Coil 2", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"Coil 3", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"Number of Layers", None))
        self.label_36.setText("")
        self.label_37.setText(QCoreApplication.translate("Form", u"ERROR STATUS", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"Number of Turns", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"Inner Radius", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"Outer Radius", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"Number of Layers", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"Number of Turns", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"Inner Radius", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"Outer Radius", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"Number of Layers", None))
        self.label_24.setText(QCoreApplication.translate("Form", u"Number of Turns", None))
        self.label_25.setText(QCoreApplication.translate("Form", u"Inner Radius", None))
        self.label_26.setText(QCoreApplication.translate("Form", u"Outer Radius", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Coils Type", None))

        __sortingEnabled = self.CoilsType1.isSortingEnabled()
        self.CoilsType1.setSortingEnabled(False)
        ___qlistwidgetitem = self.CoilsType1.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("Form", u"1. Quad Coil", None));
        ___qlistwidgetitem1 = self.CoilsType1.item(1)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("Form", u"2. Compensation Coil", None));
        self.CoilsType1.setSortingEnabled(__sortingEnabled)

        self.label_20.setText(QCoreApplication.translate("Form", u"Coils Type", None))

        __sortingEnabled1 = self.CoilsType2.isSortingEnabled()
        self.CoilsType2.setSortingEnabled(False)
        ___qlistwidgetitem2 = self.CoilsType2.item(0)
        ___qlistwidgetitem2.setText(QCoreApplication.translate("Form", u"1. Quad Coil", None));
        ___qlistwidgetitem3 = self.CoilsType2.item(1)
        ___qlistwidgetitem3.setText(QCoreApplication.translate("Form", u"2. Compensation Coil", None));
        self.CoilsType2.setSortingEnabled(__sortingEnabled1)

        self.label_12.setText(QCoreApplication.translate("Form", u"Coils Type", None))

        __sortingEnabled2 = self.CoilsType3.isSortingEnabled()
        self.CoilsType3.setSortingEnabled(False)
        ___qlistwidgetitem4 = self.CoilsType3.item(0)
        ___qlistwidgetitem4.setText(QCoreApplication.translate("Form", u"1. Quad Coil", None));
        ___qlistwidgetitem5 = self.CoilsType3.item(1)
        ___qlistwidgetitem5.setText(QCoreApplication.translate("Form", u"2. Compensation Coil", None));
        self.CoilsType3.setSortingEnabled(__sortingEnabled2)

        self.label_3.setText(QCoreApplication.translate("Form", u"Type", None))

        __sortingEnabled3 = self.Type1.isSortingEnabled()
        self.Type1.setSortingEnabled(False)
        ___qlistwidgetitem6 = self.Type1.item(0)
        ___qlistwidgetitem6.setText(QCoreApplication.translate("Form", u"1. Axial", None));
        ___qlistwidgetitem7 = self.Type1.item(1)
        ___qlistwidgetitem7.setText(QCoreApplication.translate("Form", u"2. Radial", None));
        self.Type1.setSortingEnabled(__sortingEnabled3)

        self.label_13.setText(QCoreApplication.translate("Form", u"Type", None))

        __sortingEnabled4 = self.Type2.isSortingEnabled()
        self.Type2.setSortingEnabled(False)
        ___qlistwidgetitem8 = self.Type2.item(0)
        ___qlistwidgetitem8.setText(QCoreApplication.translate("Form", u"1. Axial", None));
        ___qlistwidgetitem9 = self.Type2.item(1)
        ___qlistwidgetitem9.setText(QCoreApplication.translate("Form", u"2. Radial", None));
        self.Type2.setSortingEnabled(__sortingEnabled4)

        self.label_21.setText(QCoreApplication.translate("Form", u"Type", None))

        __sortingEnabled5 = self.Type3.isSortingEnabled()
        self.Type3.setSortingEnabled(False)
        ___qlistwidgetitem10 = self.Type3.item(0)
        ___qlistwidgetitem10.setText(QCoreApplication.translate("Form", u"1. Axial", None));
        ___qlistwidgetitem11 = self.Type3.item(1)
        ___qlistwidgetitem11.setText(QCoreApplication.translate("Form", u"2. Radial", None));
        self.Type3.setSortingEnabled(__sortingEnabled5)

        self.label_6.setText(QCoreApplication.translate("Form", u"Length", None))

        __sortingEnabled6 = self.Length1.isSortingEnabled()
        self.Length1.setSortingEnabled(False)
        ___qlistwidgetitem12 = self.Length1.item(0)
        ___qlistwidgetitem12.setText(QCoreApplication.translate("Form", u"1. Full", None));
        ___qlistwidgetitem13 = self.Length1.item(1)
        ___qlistwidgetitem13.setText(QCoreApplication.translate("Form", u"2. Half", None));
        self.Length1.setSortingEnabled(__sortingEnabled6)

        self.label_14.setText(QCoreApplication.translate("Form", u"Length", None))

        __sortingEnabled7 = self.Length2.isSortingEnabled()
        self.Length2.setSortingEnabled(False)
        ___qlistwidgetitem14 = self.Length2.item(0)
        ___qlistwidgetitem14.setText(QCoreApplication.translate("Form", u"1. Full", None));
        ___qlistwidgetitem15 = self.Length2.item(1)
        ___qlistwidgetitem15.setText(QCoreApplication.translate("Form", u"2. Half", None));
        self.Length2.setSortingEnabled(__sortingEnabled7)

        self.label_22.setText(QCoreApplication.translate("Form", u"Length", None))

        __sortingEnabled8 = self.Length3.isSortingEnabled()
        self.Length3.setSortingEnabled(False)
        ___qlistwidgetitem16 = self.Length3.item(0)
        ___qlistwidgetitem16.setText(QCoreApplication.translate("Form", u"1. Full", None));
        ___qlistwidgetitem17 = self.Length3.item(1)
        ___qlistwidgetitem17.setText(QCoreApplication.translate("Form", u"2. Half", None));
        self.Length3.setSortingEnabled(__sortingEnabled8)

    # retranslateUi

